### ISSUE TITLE
Voting Answers?

### ISSUE THREAD

**Issue by f3lan** [ese-unibe-ch/ese2010-team3#14]
What's about the voting by answers? I think we should implement this too? What is your opinion?

**Comment by sbuenzli** [comment]
Do you mean that the most voted for answer should automagically be promoted to "Best Answer"? I'd oppose that, as for our customer "Best Answer" is apparently meant to be subjectively best for the questioner and not the Crowd(tm). Also, it might lead to confustion for answers actually marked "Best Answer" by a questioner. Finally: the most voted for answer will be at the top anyway due to them being sorted by vote count.

If OTOH you didn't mean any of the above, please further elaborate your idea... ;-)

**Comment by f3lan** [comment]
OOHH, this question is purly nonsense! I meant the normal voting of answers. I could not find this in issue http://github.com/ese-unibe-ch/ese2010-team3/issues#issue/10. But it still exists in milestone1. Sorry about that mess!
