### ISSUE TITLE
polish views

### ISSUE THREAD

**Issue by sbuenzli** [ese-unibe-ch/ese2010-team3#38]
Einige günstig zu implementierende Verschönerungen:
- Delete (user profile) gehört in editProfile
- Search box ersetzt oben links den "Questions" Link
- Aktionen auf Fragen/Antworten deutlicher und konsistenter voneinander abtrennen (Add a new comment, watch, delete)
- Fragen/Antworten immer in derselben Farbe (auch wenn sie als Links dienen), derzeit haben wir etwas gar viel orange
- Kompaktere Darstellung für Fragen/Antworten - derzeit passen bloss etwa fünf Ein-Zeiler auf einen Bildschirm; bei Fragen mit einer verwandten Frage und einem Kommentar gar gar keine(!)
- Daten von Kommentaren sind kaum lesbar
- Die Tabelle in showProfile wird unnötig stark horizontal gequetscht, zudem passen in die meisten Zeilen zwei Inhalte (Nick und Email, Name und Alter, etc.).
- Datenangaben als Differenz anstelle eines absoluten Datums (Play bietet dazu "date.since()")
- Im index ist der Tag-Bereich beim Mouse-over Effekt falsch gefärbt.
- Im index und der Fragen-Ansicht könnten die Nicks noch etwas kleiner sein (andererseits sind sie eigentlich weniger wichtig als die Fragen/Antworten selbst und könnten auch klein neben das Datum platziert werden), was uns schon viel Kompaktheit gewinnen würde.

**Comment by f3lan** [comment]
# Erledigt:
- Delete (user profile) gehört in editProfile
- Search box ersetzt oben links den "Questions"  Link 
- Aktionen auf Fragen/Antworten deutlicher und konsistenter voneinander abtrennen (Add a new comment, watch, delete)
- Im index ist der Tag-Bereich beim Mouse-over Effekt falsch gefärbt.
- Die Tabelle in showProfile wird unnötig stark horizontal gequetscht, zudem passen in die meisten Zeilen zwei Inhalte (Nick und Email, Name und Alter, etc.).
  - Die Zeieln sollten nun weniger fest gequetscht werden. Eine Darstellung mit zwei Inhalten wird irgendwie unübersichtlich, habe es aus diesem Grund weggelassen (wieder rückgängig gemacht)

https://github.com/flangenegger/ese2010-team3/commit/b91823e59dae409b05a046c65f62b71702fe8ad2
- Daten von Kommentaren sind kaum lesbar
- Datenangaben als Differenz anstelle eines absoluten Datums (Play bietet dazu "date.since()")
- Im index und der Fragen-Ansicht könnten die Nicks noch etwas kleiner sein (andererseits sind sie eigentlich weniger wichtig als die Fragen/Antworten selbst und könnten auch klein neben das Datum platziert werden), was uns schon viel Kompaktheit gewinnen würde.

https://github.com/flangenegger/ese2010-team3/commit/9dbd52060ac1944e28ba2812be968654ab54a70a

**Comment by sbuenzli** [comment]
Auf mein 1024x768 Display passen noch immer nur drei Fragen. Vorschläge:
- Abstände vor/nach &lt;p>s entfernen oder &lt;div>s verwenden.
- Fragen-Text weiter verkleinern.
- Abstände um Tag-Form entfernen.
- Abstände um Zwischentitel entfernen/verkleinern.

Zudem scheint uns der Hover-Effekt bei Fragen abhanden gekommen zu sein... :-(
