### ISSUE TITLE
Conclusions from Usability Testing (sample size n=1)

### ISSUE THREAD

**Issue by sbuenzli** [ese-unibe-ch/ese2010-team3#63]
- drop e-mail requirement during registration (make it an optional part of a user's profile)
- place a "New Question" link at the top of all pages
- rename "Label" to "Tag" and "Profile" to "My Profile"
- indicate if a user has already voted and allow to unvote instead of just up-/down-voting
- include usernames in a search (and maybe also comments so that all primary entities can be searched one way or the other)
- just display (extended) summaries on the homepage instead of full questions (also, prepend titles to the content during the XML import)

**Comment by f3lan** [comment]
###Erledigt###
In Issue https://github.com/ese-unibe-ch/ese2010-team3/issues#issue/67 enthalten:
- place a "New Question" link at the top of all pages
- just display (extended) summaries on the homepage instead of full questions (also, prepend titles to the content during the XML import)
- rename "Label" to "Tag" and "Profile" to "My Profile"
- drop e-mail requirement during registration (make it an optional part of a user's profile)

Neuer Issue für "include usernames in search": https://github.com/ese-unibe-ch/ese2010-team3/issues/issue/68

###Noch zu erledigen###
- indicate if a user has already voted and allow to unvote instead of just up-/down-voting

**Comment by sbuenzli** [comment]
"prepend titles to the content during XML import" zum Reviewen: https://github.com/sbuenzli/ese2010-team3/commit/7c0728c2de15459631b282d39097a5d7626e45b8

**Comment by sbuenzli** [comment]
"indicate if a user has already voted and allow to unvote instead of just up-/down-voting" zum Reviewen: https://github.com/sbuenzli/ese2010-team3/commit/c24527d592d0edbed4c11441438b34908364bda9
